Fix/validate mem and wb stages
arRISCado/arRISCado pull request #19
Opened 2023-09-03 16:59 UTC by Joao-Pedro-MB

2023-09-03 20:34 UTC, iagocaran commented on project/cpu/memory.v
>      end
Here I don't think it matters if we use blocking or non-blocking assignments. Do you have an argument on why we should change to non-blocking ones?

2023-09-03 20:42 UTC, iagocaran commented on project/cpu.v
> +        .ram_to_mem_data_out(ram_data_out)
```suggestion
        .data_out(mem_wr_data_out),
        .mem_done(mem_wr_mem_done),

        // control outputs
        .out_RegWrite(),
        .out_RegDest(),
        .out_RegDataSrc(),
        .out_PCSrc(),

        // to RAM signals
        .mem_to_ram_address(ram_address),
        .mem_to_ram_data_in(ram_data_in),
        .mem_to_ram_write_enable(ram_write_enable),

        // from RAM signals
        .ram_to_mem_data_out(ram_data_out)
```

Here you are duplicating some signals. I think you can simply rename the old ones with the new naming scheme.

2023-09-03 20:44 UTC, iagocaran commented on project/cpu/memory.v
>      output reg mem_write_enable,
```suggestion

```
Here you should rename the outputs or remove the old ones.

2023-09-03 20:45 UTC, iagocaran commented on project/cpu/memory.v
> +    output reg [31:0] data_out,        // Data output read from memory
I think that is unnecessary, as this signal is connected to register inside the memory module.

2023-09-03 20:46 UTC, iagocaran commented on project/cpu/memory.v
> +            // need to add ram here
I think ram is already there.

2023-09-04 00:02 UTC, Joao-Pedro-MB commented on project/cpu/memory.v
> +    output reg [31:0] data_out,        // Data output read from memory
I agree with u, but it was the only way I could make the tests work

2023-09-11 17:27 UTC, llTurtle22ll approved these changes

2023-09-12 19:05 UTC, jr-santos98 approved these changes

2023-09-15 15:31 UTC, llTurtle22ll approved these changes

2023-09-15 16:48 UTC, iagocaran commented on project/cpu.v
> +    wire ex_mem_MemToReg;            // Goes to WB: Esse define que se um a saida de memoria vai direto para o registrador e se zero o resultado na verdade vem da ALU
I think these comments could be in English.

2023-09-15 16:49 UTC, iagocaran commented on project/cpu.v
> +    wire if_rb_RegDest;             // Dies on Register Bank
Can we really link them directly?

2023-09-15 17:40 UTC, iagocaran commented on project/cpu/memory.v
> +    output reg [31:0] mem_addr,       // Send address ro RAM
```suggestion
    output reg [31:0] mem_addr,       // Send address to RAM
```

2023-09-15 17:41 UTC, iagocaran commented on project/cpu/memory.v
> +    output reg mem_write_enable,      // Send signal no enable write in RAM
```suggestion
    output reg mem_write_enable,      // Send signal to enable writing in RAM
```

2023-09-15 17:50 UTC, iagocaran approved these changes

2023-09-15 18:00 UTC, EltonCN requested changes

2023-09-15 18:07 UTC, iagocaran commented on project/cpu/memory.v
> +            _load = in_MemRead;
Acredito que sim.

```suggestion
            _load = MemRead;
```

2023-09-15 18:17 UTC, EltonCN approved these changes

2023-09-15 18:17 UTC, merged